name: Worflow Evento
on:
    schedule:
        - cron: "*/2 * * * *"
        - cron: "0 12 1 * *"
jobs:
    teste:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            -   name: Action de Teste
                run: echo "Action executada apena em main e features"
